  type User @model {
    id: ID!
    username: String!
    order: Order @hasMany(fields: ["orderID"])
  }
  
  type Order  @model {
    id: ID!  
    username: User  @primaryKey(sortKeyFields: ["orderId"])
    orderId: String 
    email: String
    shippingCost: Number
    shippingType: String!
    status: String!
    total: Total
    shippingDetails: ShippingDetails
    billingDetails: BillingDetails
    products: [Products]!
  }

type Total {
      amount: Number!
      currency: String!
}

type ShippingDetails {
      firstName: String!
      lastName: String!
      company: String
      country: String!
      city: String!
      address: String!
      postalCode: String!
    }
  type BillingDetails {
      firstName: String!
      lastName: String!
      company: String
      country: String!
      city: String!
      address: String!
      postalCode: String!

  }

  type Products {
    id: String!
    price: Number!
    currency: String!
    quantity: Number!
  }